---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: myblog
  name: myblog
spec:
  type: "LoadBalancer"
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: myblog
