apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myblog
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myblog
        name: myblog
    spec:
      containers:
      - name: myblog
        image: gpjonesii/myblog:latest
        ports:
        - containerPort: 80
